---
- hosts: docker
  remote_user: "{{remote_user}}"
  become: yes
  become_method: sudo
  serial: 1          //define the action will be done one by one
  roles:
  - role: common     //define 'common' role should be apply to hosts
  - role: docker     //define 'docker' role should be apply to hosts